<a href="https://colab.research.google.com/github/sophiadto1/Data-Science/blob/main/dela_Torre_Orosz_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab #3

### Loops

In [1]:
for i in range(100): #provides numbers from 0-99
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [2]:
for i in range(5,8): #provides number 5-7
    print(i)

5
6
7


In [3]:
for i in range(3): #provides numbers 0-2
    print( "Test Number: " , i ) #prints with "Test Number:"

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [7]:
def square(x):
    return x**2 #how to square a number

In [8]:
square(5) #squaring 5

25

In [11]:
square(square(2)) #sqauring 2, then squaring 4

16

In [12]:
square(square(square(2)))  #sqauring 2, next squaring 4 and finally squaring 16


256

In [13]:
square(123456) 

15241383936

In [14]:
square(square(5)) #sqauring 5, then squaring 25

625

In [15]:
def add_two(x):
    return x+2 #creating a function to add two to x 

In [16]:
add_two(5) #x=5, so the function is 2+5=

7

In [17]:
square(add_two(5)) #using the same function 2+5=7, then sqauring 7 

49

### Logical Branching

In [18]:
choice = "apple" #setting up variables

In [19]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.") #setting up function, so if it equals apple, the function will print "You choose apples", if it doesn't then it will print "You did not choose apples"

You choose apples.


In [24]:
choice = "orange" #setting up new variable

In [23]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.") #same as function above

You choose apples.


In [22]:
choice = "apple"

In [27]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!") #new function between apples and oranges 

You choose oranges.
Thank you, shop again!


### User Input

In [30]:
choice = input("Please enter your choice (i.e. apple): ") #function allows user to put in choice 

Please enter your choice (i.e. apple): apple


In [31]:
choice

'apple'

In [32]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [35]:
import numpy as np

In [37]:
np.random.random() #creates random number

0.738086687044633

In [39]:
np.random.random() > 0.5 #states that if the random number is >0.5, then the statement is true, if not then it is false

False

In [41]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails") #setting up new function so if random number is >0.5, then it will be "heads" and if not it will be "tails"

In [49]:
flip_coin() #generating function

Tails


### Graphics Output

In [45]:
from IPython.core.display import display, HTML #allows python to display text

In [46]:
display(HTML('<h1>Hello, world!</h1>')) #displaying text "Hello World!"

In [53]:
def coin():
  return np.random.randint(2) #sets up random integer between 0-1

In [54]:
coin()

0

In [50]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #displaying the url 

In [56]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #setting up the variables to look like the inserted images

In [52]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [57]:
show_img(heads) #showing what heads will look like

In [58]:
show_img(tails) #showing what tails will look like 

In [59]:
def flip_coin(): #setting up function to know when to display heads or tails 

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [60]:
flip_coin()

In [61]:
for i in range(5): #flips coin 5 times
    flip_coin()

In [62]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [65]:
def shuffle(x): #setting up function
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [66]:
a = np.arange(52) #setting the range for a deck of cards 

In [67]:
shuffle(a) #shuffling numbers between 0-51

array([27, 20, 38, 10,  3, 18, 48, 17,  0,  7, 30, 33, 22, 12, 40, 37, 45,
       47,  9, 23, 50, 43,  5, 28, 15, 19, 39,  2, 36, 24, 34, 42, 13, 31,
       21, 16, 51, 29,  6, 26, 49,  1, 11, 44, 41, 35, 25,  8, 32,  4, 46,
       14])

In [68]:
np.random.permutation(52) #generating random numbers between 0-51

array([11, 34, 30,  7, 49, 32, 16, 31, 42, 26, 23,  5, 40, 14,  6,  8, 25,
       17, 45, 51, 37,  3, 10, 50, 46, 39, 47, 12, 33,  9, 41, 15, 27, 38,
       28, 29, 21, 13,  2, 18,  0, 24, 44, 36,  1, 48, 19, 20, 22,  4, 35,
       43])

### Speed Test

In [69]:
%%timeit  #seeing how fast the shuffle will be
shuffle(a)

128 µs ± 5.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
%%timeit
np.random.permutation(52)

2.4 µs ± 58.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [71]:
import numpy as np

In [72]:
np.random.permutation(52) #random numbers between 0-51

array([47, 19, 45, 42, 50, 49, 33, 17, 23, 35, 12, 40, 21, 37, 10, 34, 27,
       30, 39, 44, 13, 28, 24, 15, 38, 51, 11,  1, 29,  3,  8,  4, 48,  0,
       18, 41, 32, 36, 25,  5, 14,  2, 26, 43, 16, 46, 31,  9, 22,  6,  7,
       20])

In [73]:
cards = np.random.permutation(52)

In [74]:
cards

array([26, 16, 23, 22, 38, 40, 30, 47, 48, 32,  6,  7, 21, 39, 11,  9, 15,
       44, 12,  5, 42,  2, 19, 10, 34, 50, 49, 29,  4,  0, 41,  1, 18,  3,
        8, 28, 33, 27, 37, 35, 51, 13, 20, 31, 43, 24, 25, 14, 17, 45, 46,
       36])

In [75]:
cards[0] #asking to pick the first card listed above 

26

In [76]:
cards[1] #picking the second number from the array 

16

In [77]:
cards[2] #picking third number from array 

23

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) #makes 4 rows and 13 columns 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [78]:
np.arange(52).reshape(4,13)%13 #makes 4 rows and 13  columns with numbers 0-12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [82]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #setting up new function

In [83]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit] #stating how to define outputs 

In [84]:
card_name(0) #defining what name of card 1 is 

'Ace of Clubs'

In [86]:
card_name(51) #defining the name of card 50 is

'King of Diamonds'

In [87]:
cards = np.random.permutation(52)

In [88]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1]) #stating new function

In [89]:
top_of_deck, second_card_in_deck, last_card_in_deck #asking for outputs of function 

('Seven of Clubs', 'King of Hearts', 'Three of Clubs')

In [91]:
for i in range(5):
    print(card_name(cards[i])) #for cards 0-4 display name

Seven of Clubs
King of Hearts
Five of Spades
Ten of Spades
Jack of Hearts


In [92]:
for i in range(15):
    print(card_name(cards[i])) #display names for cards 0-14

Seven of Clubs
King of Hearts
Five of Spades
Ten of Spades
Jack of Hearts
Four of Spades
Four of Diamonds
Three of Diamonds
Seven of Spades
Four of Clubs
Ace of Spades
Ace of Hearts
Two of Clubs
Five of Clubs
Seven of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [93]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #images that will display 
card_url_tail = ".png"

In [94]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] #setting up new function

In [105]:
i = np.random.randint(4) #display random number between 0-3
j = np.random.randint(13) #display random number between 0-12

In [106]:
i,j

(1, 6)

In [97]:
suit[i]

's'

In [98]:
card[j]

'4'

In [107]:
from IPython.core.display import display, HTML

In [108]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) #inserting image 

In [109]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [110]:
show_img(img)

In [111]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [112]:
card_image(3)

'k4'

In [113]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img) #displaying image 

In [114]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img) #displaying images for cards 0-51